import html2canvas from "html2canvas";
import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { formatDateTimeWithLocale, formatDate } from "@/utils/dateUtils";

const getTimezoneLabel = (timezone) => {
  try {
    const now = new Date();
    const longName = new Intl.DateTimeFormat("en-US", {
      timeZone: timezone,
      timeZoneName: "long",
    })
      .formatToParts(now)
      .find((p) => p.type === "timeZoneName")?.value || timezone;

    const shortOffset = new Intl.DateTimeFormat("en-US", {
      timeZone: timezone,
      timeZoneName: "shortOffset",
    })
      .formatToParts(now)
      .find((p) => p.type === "timeZoneName")?.value || "";

    return shortOffset ? `${longName} (${shortOffset})` : longName;
  } catch {
    return timezone || "UTC";
  }
};

// Layout & font sizes
const FONT_TITLE = 16;
const FONT_SECTION = 14;
const FONT_LABEL = 9;
const FONT_VALUE = 9;
const FONT_PAGENUM = 9;

const LEFT_MARGIN = 42.52;
const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const LINE_HEIGHT = 14.17;
const CHART_MAX_HEIGHT = 283.47;
const SPACING = 22.68;
const COLOR_PRIMARY = rgb(0, 0.467, 0.714); // #0077b6
const COLOR_TEXT_MAIN = rgb(0.12, 0.16, 0.22); // #1f2937
const COLOR_TEXT_SECONDARY = rgb(0.42, 0.46, 0.53); // #6b7280
const COLOR_BORDER = rgb(0.9, 0.9, 0.9);
const COLOR_BG_LIGHT = rgb(0.97, 0.98, 1);

// Helper to convert hex to pdf-lib RGB
const hexToPdfRgb = (hex) => {
  if (!hex || typeof hex !== "string") return COLOR_PRIMARY;
  const cleanHex = hex.replace("#", "");
  const r = parseInt(cleanHex.substring(0, 2), 16) / 255;
  const g = parseInt(cleanHex.substring(2, 4), 16) / 255;
  const b = parseInt(cleanHex.substring(4, 6), 16) / 255;
  return rgb(r || 0, g || 0, b || 0);
};

// Convert any image URL (JPEG, PNG, WebP, SVG…) to PNG bytes via canvas
const fetchImageAsPngBytes = (url) =>
  new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth || 300;
      canvas.height = img.naturalHeight || 150;
      canvas.getContext("2d").drawImage(img, 0, 0);
      canvas.toBlob((blob) => {
        if (!blob) return reject(new Error("canvas toBlob failed"));
        blob.arrayBuffer().then(resolve).catch(reject);
      }, "image/png");
    };
    img.onerror = () => reject(new Error("Image failed to load"));
    img.src = url;
  });

// Load Cairo fonts for Arabic support
const loadCairoFonts = async (pdf) => {
  try {
    const regularResponse = await fetch("/fonts/cairo/Cairo-Regular.ttf");
    const regularBytes = await regularResponse.arrayBuffer();
    const font = await pdf.embedFont(regularBytes);

    const boldResponse = await fetch("/fonts/cairo/Cairo-Bold.ttf");
    const boldBytes = await boldResponse.arrayBuffer();
    const bold = await pdf.embedFont(boldBytes);

    return { font, bold };
  } catch (error) {
    console.error("Error loading Cairo fonts:", error);
    return null;
  }
};

// pdf-lib has no bidi support — parentheses get visually mirrored in RTL rendering.
const fixParens = (text, isRTL) =>
  isRTL
    ? String(text).replace(/\(/g, "\x00").replace(/\)/g, "(").replace(/\x00/g, ")")
    : String(text);

const getTextX = (text, x, pageWidth, margin, isRTL, align = "left", font, fontSize) => {
  if (isRTL && align === "left") {
    const textWidth = font.widthOfTextAtSize(text, fontSize);
    return pageWidth - margin - textWidth;
  }
  return x;
};

const drawConfidentialFooter = (page, pageWidth, font, language, margin = LEFT_MARGIN) => {
  const fontSize = 8;
  const color = COLOR_TEXT_SECONDARY;
  const y = 10;

  if (language === "ar") {
    const arabicPart = "سري - تم إنشاؤه بواسطة ";
    const englishPart = "EventPass";
    page.drawText(englishPart, { x: margin, y, size: fontSize, font, color });
    page.drawText(arabicPart, { x: margin + font.widthOfTextAtSize(englishPart, fontSize), y, size: fontSize, font, color });
  } else {
    const text = "Confidential - Generated by EventPass";
    page.drawText(text, { x: margin, y, size: fontSize, font, color });
  }
};

const drawKpiCards = async (page, cards, y, pageWidth, margin, font, boldFont, language, isRTL) => {
  const gap = 8;
  const totalWidth = pageWidth - margin * 2;
  const cardHeight = 70;

  if (y - cardHeight < margin) return y;

  // Calculate widths: Normal cards get 1 unit, Highlight gets 2.5 units
  const highlightCard = cards.find(c => c.isHighlight);
  const normalCards = cards.filter(c => !c.isHighlight);
  const totalUnits = normalCards.length + (highlightCard ? 2.5 : 0);
  const unitWidth = (totalWidth - (cards.length - 1) * gap) / totalUnits;

  let currentX = isRTL ? pageWidth - margin : margin;

  // Reorder for RTL drawing if needed
  const drawingOrder = isRTL ? [...cards].reverse() : cards;

  for (const card of drawingOrder) {
    const isH = card.isHighlight;
    const cWidth = isH ? unitWidth * 2.5 : unitWidth;
    const drawX = isRTL ? currentX - cWidth : currentX;

    if (isH) {
      // Draw Highlight Card
      const sideBarWidth = 3;
      page.drawRectangle({
        x: drawX,
        y: y - cardHeight,
        width: cWidth,
        height: cardHeight,
        color: rgb(0.97, 0.98, 1),
      });
      page.drawRectangle({
        x: isRTL ? drawX + cWidth - sideBarWidth : drawX,
        y: y - cardHeight,
        width: sideBarWidth,
        height: cardHeight,
        color: rgb(0.39, 0.4, 0.95),
      });

      const labelSize = 6;
      const valueSize = 9;
      const padding = 8;
      const innerX = isRTL ? drawX + cWidth - padding - sideBarWidth : drawX + padding + sideBarWidth;

      page.drawText(String(card.label).toUpperCase(), {
        x: isRTL ? drawX + cWidth - padding - sideBarWidth - boldFont.widthOfTextAtSize(String(card.label).toUpperCase(), labelSize) : innerX,
        y: y - 15,
        size: labelSize,
        font: boldFont,
        color: rgb(0.39, 0.4, 0.95),
      });

      const questionText = `"${card.value}"`;
      const maxTextWidth = cWidth - padding * 2 - sideBarWidth;
      const words = questionText.split(" ");
      let lines = [];
      let currentLine = "";
      for (const word of words) {
        const testLine = currentLine ? `${currentLine} ${word}` : word;
        if (font.widthOfTextAtSize(testLine, valueSize) > maxTextWidth) {
          lines.push(currentLine);
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }
      lines.push(currentLine);
      lines = lines.slice(0, 2);

      let textY = y - 30;
      lines.forEach(line => {
        const lineX = isRTL ? drawX + cWidth - padding - sideBarWidth - font.widthOfTextAtSize(line, valueSize) : innerX;
        page.drawText(line, { x: lineX, y: textY, size: valueSize, font, color: COLOR_TEXT_MAIN });
        textY -= 11;
      });

      if (card.subValue) {
        const subX = isRTL ? drawX + cWidth - padding - sideBarWidth - font.widthOfTextAtSize(String(card.subValue), 7) : innerX;
        page.drawText(String(card.subValue), { x: subX, y: y - 60, size: 7, font: boldFont, color: rgb(0.39, 0.4, 0.95) });
      }
    } else {
      // Draw Normal Card
      page.drawRectangle({
        x: drawX,
        y: y - cardHeight,
        width: cWidth,
        height: cardHeight,
        color: rgb(1, 1, 1),
        borderColor: COLOR_BORDER,
        borderWidth: 1,
      });

      const vSize = 14;
      const lSize = 7;
      const vWidth = boldFont.widthOfTextAtSize(String(card.value), vSize);
      const lWidth = font.widthOfTextAtSize(card.label, lSize);

      page.drawText(String(card.value), {
        x: drawX + (cWidth - vWidth) / 2,
        y: y - 35,
        size: vSize,
        font: boldFont,
        color: card.color ? hexToPdfRgb(card.color) : COLOR_PRIMARY,
      });

      page.drawText(card.label, {
        x: drawX + (cWidth - lWidth) / 2,
        y: y - 52,
        size: lSize,
        font,
        color: COLOR_TEXT_SECONDARY,
      });
    }

    if (isRTL) currentX -= cWidth + gap;
    else currentX += cWidth + gap;
  }

  return y - cardHeight - gap;
};


const renderLabelValue = (page, label, value, x, y, pageWidth, margin, isRTL, font, boldFont, fontSize) => {
  const colon = ":";
  const spacing = 2.8;

  if (isRTL) {
    const valueText = String(value);
    const labelText = String(label);
    const labelWidth = boldFont.widthOfTextAtSize(labelText, fontSize);
    const colonWidth = font.widthOfTextAtSize(colon, fontSize);
    const valueWidth = font.widthOfTextAtSize(valueText, fontSize);
    const labelX = pageWidth - margin - labelWidth;
    const colonX = labelX - spacing - colonWidth;
    const valueX = colonX - spacing - valueWidth;

    page.drawText(valueText, { x: valueX, y, size: fontSize, font });
    page.drawText(colon, { x: colonX, y, size: fontSize, font });
    page.drawText(labelText, { x: labelX, y, size: fontSize, font: boldFont });
  } else {
    const labelText = `${label}${colon} `;
    const labelWidth = boldFont.widthOfTextAtSize(labelText, fontSize);
    page.drawText(labelText, { x, y, size: fontSize, font: boldFont });
    page.drawText(String(value), { x: x + labelWidth, y, size: fontSize, font });
  }
};

const addEventHeader = async (
  pdf,
  page,
  eventInfo,
  pageWidth,
  margin,
  surveyInfo = null,
  _language = "en",
  isRTL = false,
  translations = {},
  font,
  boldFont,
  timezone = null
) => {
  if (!eventInfo) return PAGE_HEIGHT - margin;

  let currentY = PAGE_HEIGHT - margin;

  const eventName = String(eventInfo.name || "");
  const eventNameX = getTextX(eventName, margin, pageWidth, margin, isRTL, "left", boldFont, FONT_TITLE);
  page.drawText(eventName, {
    x: eventNameX,
    y: currentY,
    size: FONT_TITLE,
    font: boldFont,
    color: rgb(0.12, 0.16, 0.22),
  });
  currentY -= 14.17;

  if (eventInfo.subtitle) {
    renderLabelValue(page, eventInfo.subtitleLabel || "Event Name", String(eventInfo.subtitle), margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }

  const fromLabel = translations.from || "From";
  const toLabel = translations.to || "To";
  const venueLabel = translations.venue || "Venue";
  const registrationsLabel = translations.registrations || "Registrations";

  if (eventInfo.startDate || eventInfo.startDateFormatted) {
    const fromDate = eventInfo.startDateFormatted || formatDate(eventInfo.startDate);
    renderLabelValue(page, fromLabel, fromDate, margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }
  if (eventInfo.endDate || eventInfo.endDateFormatted) {
    const toDate = eventInfo.endDateFormatted || formatDate(eventInfo.endDate);
    renderLabelValue(page, toLabel, toDate, margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }
  if (eventInfo.venue && eventInfo.venue !== "N/A") {
    renderLabelValue(page, venueLabel, String(eventInfo.venue), margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }
  if (eventInfo.registrations !== undefined && eventInfo.registrations !== null) {
    const registrationsValue = eventInfo.registrationsFormatted !== undefined
      ? eventInfo.registrationsFormatted
      : String(eventInfo.registrations);
    renderLabelValue(page, registrationsLabel, registrationsValue, margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }

  if (surveyInfo) {
    const titleOfSurveyLabel = translations.titleOfSurvey || "Title of survey";
    const descriptionLabel = translations.description || "Description";
    const totalResponsesLabel = translations.totalResponses || "Total Responses";

    if (surveyInfo.title) {
      renderLabelValue(page, titleOfSurveyLabel, String(surveyInfo.title), margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
      currentY -= LINE_HEIGHT;
    }

    if (surveyInfo.description) {
      const description = String(surveyInfo.description || "");
      const maxWidth = (pageWidth - margin * 2) * 0.8;

      if (isRTL) {
        const labelText = String(descriptionLabel);
        const colon = ":";
        const spacing = 2.8;
        const labelWidth = boldFont.widthOfTextAtSize(labelText, FONT_LABEL);
        const colonWidth = font.widthOfTextAtSize(colon, FONT_LABEL);
        const labelX = pageWidth - margin - labelWidth;
        const colonX = labelX - spacing - colonWidth;
        const availableWidth = colonX - margin - spacing;

        const words = description.split(" ");
        const lines = [];
        let currentLine = "";
        for (const word of words) {
          const testLine = currentLine ? `${currentLine} ${word}` : word;
          if (font.widthOfTextAtSize(testLine, FONT_VALUE) > availableWidth && currentLine) {
            lines.push(currentLine);
            currentLine = word;
          } else {
            currentLine = testLine;
          }
        }
        if (currentLine) lines.push(currentLine);

        page.drawText(labelText, { x: labelX, y: currentY, size: FONT_LABEL, font: boldFont });
        page.drawText(colon, { x: colonX, y: currentY, size: FONT_LABEL, font });

        if (lines.length > 0 && lines[0]) {
          const firstLineWidth = font.widthOfTextAtSize(lines[0], FONT_VALUE);
          page.drawText(lines[0], { x: colonX - spacing - firstLineWidth, y: currentY, size: FONT_VALUE, font });
          currentY -= LINE_HEIGHT;
          for (let i = 1; i < lines.length; i++) {
            const lineWidth = font.widthOfTextAtSize(lines[i], FONT_VALUE);
            page.drawText(lines[i], { x: pageWidth - margin - lineWidth, y: currentY, size: FONT_VALUE, font });
            currentY -= LINE_HEIGHT;
          }
        } else {
          currentY -= LINE_HEIGHT;
        }
      } else {
        const labelText = `${descriptionLabel}: `;
        const labelWidth = boldFont.widthOfTextAtSize(labelText, FONT_LABEL);
        page.drawText(labelText, { x: margin, y: currentY, size: FONT_LABEL, font: boldFont });

        const descriptionStartX = margin + labelWidth;
        const availableWidth = maxWidth - labelWidth;
        const words = description.split(" ");
        const lines = [];
        let currentLine = "";
        for (const word of words) {
          const testLine = currentLine ? `${currentLine} ${word}` : word;
          if (font.widthOfTextAtSize(testLine, FONT_VALUE) > availableWidth && currentLine) {
            lines.push(currentLine);
            currentLine = word;
          } else {
            currentLine = testLine;
          }
        }
        if (currentLine) lines.push(currentLine);

        if (lines.length > 0 && lines[0]) {
          page.drawText(lines[0], { x: descriptionStartX, y: currentY, size: FONT_VALUE, font });
          currentY -= LINE_HEIGHT;
          for (let i = 1; i < lines.length; i++) {
            page.drawText(lines[i], { x: margin, y: currentY, size: FONT_VALUE, font });
            currentY -= LINE_HEIGHT;
          }
        } else {
          currentY -= LINE_HEIGHT;
        }
      }
    }

    if (surveyInfo.totalResponses !== undefined && surveyInfo.totalResponses !== null) {
      const totalResponsesValue = surveyInfo.totalResponsesFormatted !== undefined
        ? surveyInfo.totalResponsesFormatted
        : String(surveyInfo.totalResponses);
      renderLabelValue(page, totalResponsesLabel, totalResponsesValue, margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
      currentY -= LINE_HEIGHT;
    }
  }

  {
    const exportedAtLabel = translations.exportedAt || "Exported At";
    const exportedAtValue = (() => {
      try {
        return new Intl.DateTimeFormat("en-US", {
          year: "numeric", month: "short", day: "numeric",
          hour: "2-digit", minute: "2-digit",
          ...(timezone ? { timeZone: timezone } : {}),
        }).format(new Date());
      } catch { return new Date().toLocaleString(); }
    })();
    renderLabelValue(page, exportedAtLabel, exportedAtValue, margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }

  if (timezone) {
    const tzLabel = getTimezoneLabel(timezone);
    const timezoneKey = translations.timezone || "Timezone";
    renderLabelValue(page, timezoneKey, tzLabel, margin, currentY, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
    currentY -= LINE_HEIGHT;
  }

  // Branding line: "Presented by WhiteWall  |  Powered by EventPass"
  {
    const BRAND_SIZE = 8;
    const presentedBy = translations.presentedBy || "Presented by";
    const poweredBy = translations.poweredBy || "Powered by";
    const grayColor = rgb(0.55, 0.55, 0.55);
    const darkColor = rgb(0.12, 0.16, 0.22);
    const blueColor = rgb(0, 0.467, 0.714);

    // Build pieces: ["Presented by ", "WhiteWall", "   |   ", "Powered by ", "Event", "Pass"]
    const pieces = isRTL
      ? [
          { text: "Event", font: boldFont, color: darkColor },
          { text: "Pass", font: boldFont, color: blueColor },
          { text: ` ${poweredBy}   |   `, font, color: grayColor },
          { text: "WhiteWall", font: boldFont, color: darkColor },
          { text: ` ${presentedBy}`, font, color: grayColor },
        ]
      : [
          { text: `${presentedBy} `, font, color: grayColor },
          { text: "WhiteWall", font: boldFont, color: darkColor },
          { text: "   |   ", font, color: grayColor },
          { text: `${poweredBy} `, font, color: grayColor },
          { text: "Event", font: boldFont, color: darkColor },
          { text: "Pass", font: boldFont, color: blueColor },
        ];

    const totalW = pieces.reduce((sum, p) => sum + p.font.widthOfTextAtSize(p.text, BRAND_SIZE), 0);
    let drawX = (pageWidth - totalW) / 2;

    pieces.forEach((p) => {
      page.drawText(p.text, { x: drawX, y: currentY, size: BRAND_SIZE, font: p.font, color: p.color });
      drawX += p.font.widthOfTextAtSize(p.text, BRAND_SIZE);
    });

    currentY -= LINE_HEIGHT;
  }

  page.drawLine({
    start: { x: margin, y: currentY },
    end: { x: pageWidth - margin, y: currentY },
    thickness: 0.5,
    color: COLOR_BORDER,
  });

  return currentY - 15;
};

// Generic KPI card row — takes array of { label, value, rgbColor }
const drawSimpleKpiCards = (page, cards, yPosition, pageWidth, margin, font, boldFont, isRTL = false) => {
  if (!cards.length) return yPosition;
  const count = cards.length;
  const gap = 10;
  const cardWidth = (pageWidth - margin * 2 - (count - 1) * gap) / count;
  const cardHeight = 68;
  const valueSize = 20;
  const labelSize = 9;
  const labelLineHeight = 11;

  const ordered = isRTL ? [...cards].reverse() : cards;
  ordered.forEach((card, i) => {
    const cardX = margin + i * (cardWidth + gap);
    const cardY = yPosition - cardHeight;

    page.drawRectangle({
      x: cardX, y: cardY, width: cardWidth, height: cardHeight,
      color: rgb(1, 1, 1),
      borderColor: rgb(0.878, 0.878, 0.878),
      borderWidth: 0.75,
    });

    // Colored top stripe on card
    page.drawRectangle({
      x: cardX, y: cardY + cardHeight - 4, width: cardWidth, height: 4,
      color: card.rgbColor,
    });

    const valueText = String(card.value);
    const valueWidth = boldFont.widthOfTextAtSize(valueText, valueSize);
    page.drawText(valueText, {
      x: Math.max(cardX + 2, cardX + (cardWidth - valueWidth) / 2),
      y: cardY + 38,
      size: valueSize, font: boldFont, color: card.rgbColor,
    });

    const labelText = String(card.label);
    const maxLabelWidth = cardWidth - 8;
    const words = labelText.split(" ");
    const lines = [];
    let cur = "";
    for (const word of words) {
      const test = cur ? `${cur} ${word}` : word;
      if (font.widthOfTextAtSize(test, labelSize) > maxLabelWidth && cur) {
        lines.push(cur);
        cur = word;
      } else {
        cur = test;
      }
    }
    if (cur) lines.push(cur);

    const labelStartY = lines.length === 1 ? cardY + 16 : cardY + 22;
    lines.forEach((line, li) => {
      const lw = font.widthOfTextAtSize(line, labelSize);
      page.drawText(line, {
        x: Math.max(cardX + 2, cardX + (cardWidth - lw) / 2),
        y: labelStartY - li * labelLineHeight,
        size: labelSize, font, color: rgb(0.459, 0.459, 0.459),
      });
    });
  });

  return yPosition - cardHeight;
};

const drawPrintStatsKpiCards = (page, eventInfo, yPosition, pageWidth, margin, font, boldFont, translations, isRTL = false) => {
  const cards = [
    { label: fixParens(translations.totalBadgePrints || "Total Badge Prints", isRTL),     value: String(eventInfo.totalPrints    ?? 0), rgbColor: rgb(0,      0.467, 0.714) },
    { label: fixParens(translations.noPrints        || "0 Prints (Never Printed)", isRTL), value: String(eventInfo.noPrintCount   ?? 0), rgbColor: rgb(0.937, 0.267, 0.267) },
    { label: fixParens(translations.onePrint        || "1 Print", isRTL),                  value: String(eventInfo.onePrintCount  ?? 0), rgbColor: rgb(0.961, 0.620, 0.043) },
    { label: fixParens(translations.multiPrint      || "Multi-Print", isRTL),         value: String(eventInfo.multiPrintCount ?? 0), rgbColor: rgb(0.063, 0.725, 0.506) },
    { label: fixParens(translations.multiPrintRate  || "Multi-Print Rate", isRTL),         value: `${eventInfo.multiPrintRate ?? "0.00"}%`, rgbColor: rgb(0.545, 0.361, 0.965) },
  ];
  return drawSimpleKpiCards(page, cards, yPosition, pageWidth, margin, font, boldFont, isRTL);
};

export const exportChartsToPDF = async (
  chartRefs,
  fieldLabels,
  chartDataArray,
  eventInfo,
  surveyInfo = null,
  language = "en",
  dir = "ltr",
  translations = {},
  timezone = null
) => {
  // Robustness for old calls where language was the 5th argument
  let activeSurveyInfo = surveyInfo;
  let activeLanguage = language;
  let activeDir = dir;
  let activeTranslations = translations;
  let activeTimezone = timezone;

  if (typeof surveyInfo === "string" && (surveyInfo === "en" || surveyInfo === "ar")) {
    activeTimezone = activeTranslations;
    activeTranslations = activeDir;
    activeDir = activeLanguage;
    activeLanguage = surveyInfo;
    activeSurveyInfo = null;
  }

  const pdf = await PDFDocument.create();
  pdf.registerFontkit(fontkit);

  const isRTL = activeDir === "rtl";
  const pageWidth = PAGE_WIDTH;
  const pageHeight = PAGE_HEIGHT;
  const margin = LEFT_MARGIN;
  const chartWidth = pageWidth - margin * 2;
  const maxChartHeight = CHART_MAX_HEIGHT;
  const spacing = SPACING;

  let font, boldFont;
  const fonts = await loadCairoFonts(pdf);
  if (fonts) {
    font = fonts.font;
    boldFont = fonts.bold;
  } else {
    font = await pdf.embedFont("Helvetica");
    boldFont = await pdf.embedFont("Helvetica-Bold");
  }

  // First content page
  let page = pdf.addPage([pageWidth, pageHeight]);
  let yPosition = pageHeight - margin;

  // Header and Branding — show event logo in top corner
  if (eventInfo?.logoUrl) {
    try {
      const logoBytes = await fetchImageAsPngBytes(eventInfo.logoUrl);
      const logoImage = await pdf.embedPng(logoBytes);
      const logoMaxW = 240;
      const logoMaxH = 100;
      const scale = Math.min(logoMaxW / logoImage.width, logoMaxH / logoImage.height);
      const logoDims = logoImage.scale(scale);
      page.drawImage(logoImage, {
        x: isRTL ? margin : pageWidth - margin - logoDims.width,
        y: pageHeight - margin / 2 - logoDims.height,
        width: logoDims.width,
        height: logoDims.height,
      });
    } catch (e) { console.warn("Could not load event logo for header corner", e); }
  }

  yPosition = await addEventHeader(
    pdf,
    page,
    eventInfo,
    pageWidth,
    margin,
    activeSurveyInfo,
    activeLanguage,
    isRTL,
    activeTranslations,
    font,
    boldFont,
    activeTimezone
  );

  // Summary KPIs Section
  if (eventInfo.summaryCards) {
    yPosition = await drawKpiCards(
      page,
      eventInfo.summaryCards,
      yPosition - 10,
      pageWidth,
      margin,
      font,
      boldFont,
      activeLanguage,
      isRTL
    );
  }
  yPosition -= spacing;

  // Top-level KPI summary cards
  if (eventInfo?.uniqueScanned !== undefined && eventInfo?.totalRegistrations !== undefined) {
    // EventReg / CheckIn
    const secLabel = translations.registrationAttendance || "Registration & Attendance";
    const secX = getTextX(secLabel, margin, pageWidth, margin, isRTL, "left", boldFont, FONT_SECTION);
    page.drawText(secLabel, { x: secX, y: yPosition, size: FONT_SECTION, font: boldFont, color: rgb(0.12, 0.16, 0.22) });
    yPosition -= 20;

    const regCards = [
      { label: fixParens(translations.totalRegistrations || "Total Registrations", isRTL), value: String(eventInfo.totalRegistrations ?? 0),       rgbColor: rgb(0, 0.467, 0.714) },
      { label: fixParens(translations.totalScanned || "Total Scanned", isRTL),             value: String(eventInfo.uniqueScanned ?? 0),            rgbColor: rgb(0.008, 0.518, 0.780) },
      { label: fixParens(translations.scanRate || "Scan Rate", isRTL),                     value: `${eventInfo.scanRate ?? "0.00"}%`,               rgbColor: rgb(0.024, 0.714, 0.831) },
      { label: fixParens(translations.totalBadgePrints || "Total Badge Prints", isRTL),    value: String(eventInfo.totalPrints ?? 0),              rgbColor: rgb(0.486, 0.227, 0.929) },
      { label: fixParens(translations.multiPrintRate || "Multi-Print Rate", isRTL),        value: `${eventInfo.multiPrintRate ?? "0.00"}%`,         rgbColor: rgb(0.055, 0.647, 0.914) },
    ];
    yPosition = drawSimpleKpiCards(page, regCards, yPosition, pageWidth, margin, font, boldFont, isRTL);
    yPosition -= spacing;

  } else if (eventInfo?.uniqueVoters !== undefined) {
    // VoteCast
    const secLabel = translations.pollOverview || "Poll Overview";
    const secX = getTextX(secLabel, margin, pageWidth, margin, isRTL, "left", boldFont, FONT_SECTION);
    page.drawText(secLabel, { x: secX, y: yPosition, size: FONT_SECTION, font: boldFont, color: rgb(0.12, 0.16, 0.22) });
    yPosition -= 20;

    const hasParticipationRate = eventInfo.participationRate !== undefined && eventInfo.participationRate !== null;
    const voteCards = [
      { label: fixParens(translations.totalVotes || "Total Votes Cast", isRTL),         value: String(eventInfo.totalVotes ?? 0),    rgbColor: rgb(0, 0.467, 0.714) },
      ...(hasParticipationRate ? [{ label: fixParens(translations.participationRate || "Participation Rate", isRTL), value: `${eventInfo.participationRate}%`, rgbColor: rgb(0.008, 0.518, 0.780) }] : []),
      { label: fixParens(translations.questionCount || "Question Count", isRTL),        value: String(eventInfo.questionCount ?? 0), rgbColor: rgb(0.024, 0.714, 0.831) },
    ];
    yPosition = drawSimpleKpiCards(page, voteCards, yPosition, pageWidth, margin, font, boldFont, isRTL);
    yPosition -= spacing;
  }

  let isFirstChart = true;

  const ensureSpace = async (needed) => {
    if (yPosition < needed + margin) {
      page = pdf.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - margin;
    }
  };

  // Chart sections
  for (let i = 0; i < chartRefs.length; i++) {
    const chartElement = chartRefs[i];
    const fieldLabel = fieldLabels[i];
    const chartData = chartDataArray[i];
    if (!chartElement) continue;

    try {
      const legendElements = chartElement.querySelectorAll(
        '.MuiChartsLegend-root, [class*="MuiChartsLegend"]'
      );
      legendElements.forEach((el) => (el.style.display = "none"));

      const canvas = await html2canvas(chartElement, {
        scale: 2,
        backgroundColor: "#ffffff",
        logging: false,
        useCORS: true,
        allowTaint: true,
        onclone: (_document, element) => {
          // Ensure SVG elements have explicit dimensions so html2canvas renders them
          element.querySelectorAll("svg").forEach((svg) => {
            const rect = svg.getBoundingClientRect();
            if (!svg.getAttribute("width") && rect.width > 0) {
              svg.setAttribute("width", String(Math.ceil(rect.width)));
            }
            if (!svg.getAttribute("height") && rect.height > 0) {
              svg.setAttribute("height", String(Math.ceil(rect.height)));
            }
          });
        },
      });

      legendElements.forEach((el) => (el.style.display = ""));

      const imgData = canvas.toDataURL("image/png");
      const imgBytes = await fetch(imgData).then((res) => res.arrayBuffer());
      const chartImage = await pdf.embedPng(imgBytes);

      const imgAspectRatio = canvas.width / canvas.height;
      const chartHeight = Math.min(chartWidth / imgAspectRatio, maxChartHeight);

      const titleHeight = 14;
      const metadataHeight = chartData.chartType === "line" ? 45 : chartData.questionType || chartData.type === "multi" || chartData.type === "rating" || chartData.type === "nps" ? 14 : chartData.chartType === "pie" && (chartData.type === "text" || chartData.type === "number" || chartData.type === "multi" || chartData.questionType === "multi") && !activeSurveyInfo ? 14 : 0;
      const totalHeight = titleHeight + spacing + metadataHeight + spacing + chartHeight + spacing;

      await ensureSpace(totalHeight);

      if (yPosition - totalHeight < margin && !isFirstChart) {
        page = pdf.addPage([pageWidth, pageHeight]);
        yPosition = pageHeight - margin;
      }

      const fieldLabelX = getTextX(fieldLabel, margin, pageWidth, margin, isRTL, "left", boldFont, FONT_SECTION);
      page.drawText(fieldLabel, {
        x: fieldLabelX,
        y: yPosition,
        size: FONT_SECTION,
        font: boldFont,
        color: rgb(0.12, 0.16, 0.22),
      });
      yPosition -= 20;

      const typeLabel = activeTranslations.type || "Type";
      const topNLabel = activeTranslations.topN || "Top N";
      const intervalLabel = activeTranslations.intervalMinutes || "Interval (min)";

      if (surveyInfo && chartData) {
        const fieldType = chartData.questionType || chartData.type;
        let typeValue = "";
        if (fieldType === "multi") typeValue = "MCQ";
        else if (fieldType === "rating") typeValue = "Rating";
        else if (fieldType === "nps") typeValue = "NPS";

        if (typeValue) {
          renderLabelValue(page, typeLabel, typeValue, margin, yPosition, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
          yPosition -= LINE_HEIGHT;
        }
      }

      if (
        chartData.chartType === "pie" &&
        (chartData.type === "text" || chartData.type === "number" || chartData.type === "categorical" || chartData.type === "multi" || chartData.questionType === "multi") &&
        !surveyInfo
      ) {
        renderLabelValue(page, topNLabel, String(chartData.topN || 10), margin, yPosition, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
        yPosition -= LINE_HEIGHT;
      } else if (chartData.chartType === "line" && chartData.type === "time") {
        const startDate = chartData.startDateTimeFormatted || formatDateTimeWithLocale(chartData.startDateTime, activeLanguage);
        const endDate = chartData.endDateTimeFormatted || formatDateTimeWithLocale(chartData.endDateTime, activeLanguage);
        const intervalValue = chartData.intervalMinutesFormatted || `${chartData.intervalMinutes || 60} min`;

        renderLabelValue(page, activeTranslations.from || "From", startDate, margin, yPosition, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
        yPosition -= LINE_HEIGHT;
        renderLabelValue(page, activeTranslations.to || "To", endDate, margin, yPosition, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
        yPosition -= LINE_HEIGHT;

        const intervalBase = intervalLabel.replace(/\s*\(.*?\)\s*/, "").trim();
        if (chartData.intervalMinutesFormatted && chartData.intervalMinutesSuffix) {
          const intervalNumber = chartData.intervalMinutesFormatted;
          const intervalSuffix = chartData.intervalMinutesSuffix;
          const sp = 2.8;
          const colon = ":";

          if (isRTL) {
            const labelText = String(intervalBase);
            const labelWidth = boldFont.widthOfTextAtSize(labelText, FONT_LABEL);
            const colonWidth = font.widthOfTextAtSize(colon, FONT_LABEL);
            const numberWidth = font.widthOfTextAtSize(intervalNumber, FONT_LABEL);
            const minWidth = font.widthOfTextAtSize(intervalSuffix, FONT_LABEL);
            const spaceWidth = font.widthOfTextAtSize(" ", FONT_LABEL);
            const labelX = pageWidth - margin - labelWidth;
            const colonX = labelX - sp - colonWidth;
            const valueX = colonX - sp - numberWidth - spaceWidth - minWidth;

            page.drawText(labelText, { x: labelX, y: yPosition, size: FONT_LABEL, font: boldFont });
            page.drawText(colon, { x: colonX, y: yPosition, size: FONT_LABEL, font });
            page.drawText(intervalNumber, { x: valueX, y: yPosition, size: FONT_LABEL, font });
            page.drawText(intervalSuffix, { x: valueX + numberWidth + spaceWidth, y: yPosition, size: FONT_LABEL, font });
          } else {
            const labelText = `${intervalBase}${colon} `;
            const labelWidth = boldFont.widthOfTextAtSize(labelText, FONT_LABEL);
            const numberWidth = font.widthOfTextAtSize(intervalNumber, FONT_LABEL);
            page.drawText(labelText, { x: margin, y: yPosition, size: FONT_LABEL, font: boldFont });
            page.drawText(intervalNumber, { x: margin + labelWidth, y: yPosition, size: FONT_LABEL, font });
            page.drawText(` ${intervalSuffix}`, { x: margin + labelWidth + numberWidth, y: yPosition, size: FONT_LABEL, font });
          }
        } else {
          renderLabelValue(page, intervalBase, intervalValue, margin, yPosition, pageWidth, margin, isRTL, font, boldFont, FONT_LABEL);
        }
        yPosition -= LINE_HEIGHT;
      }

      yPosition -= spacing + 8.5;

      const chartX = isRTL ? pageWidth - margin - chartWidth : margin;
      page.drawImage(chartImage, {
        x: chartX,
        y: yPosition - chartHeight,
        width: chartWidth,
        height: chartHeight,
      });
      yPosition -= chartHeight + spacing;

      isFirstChart = false;
    } catch (error) {
      console.error(`Error capturing chart ${i}:`, error);
    }
  }

  // Response Pattern Section (VoteCast unlinked polls)
  if (eventInfo?.responsePatternQuestions?.length) {
    await ensureSpace(30);

    const sectionLabel = activeTranslations.responsePattern || "Response Pattern";
    const sectionLabelX = getTextX(sectionLabel, margin, pageWidth, margin, isRTL, "left", boldFont, FONT_SECTION);
    page.drawText(sectionLabel, { x: sectionLabelX, y: yPosition, size: FONT_SECTION, font: boldFont, color: COLOR_TEXT_MAIN });
    yPosition -= 24;

    const contentWidth = pageWidth - margin * 2;
    const barH = 7;
    const optFontSize = 8;
    const qFontSize = 10;
    const rowHeight = optFontSize + 4 + barH + 8;

    for (const q of eventInfo.responsePatternQuestions) {
      const total = (q.options || []).reduce((sum, o) => sum + (o.votes || 0), 0);
      const neededH = qFontSize + 8 + (q.options?.length || 0) * rowHeight + 12;
      await ensureSpace(neededH);

      // Question text
      const qText = fixParens(String(q.question || ""), isRTL);
      const qX = isRTL ? pageWidth - margin - boldFont.widthOfTextAtSize(qText, qFontSize) : margin;
      page.drawText(qText, { x: qX, y: yPosition, size: qFontSize, font: boldFont, color: COLOR_TEXT_MAIN });
      yPosition -= qFontSize + 8;

      for (const opt of (q.options || [])) {
        await ensureSpace(rowHeight);
        const votes = opt.votes || 0;
        const pct = total > 0 ? (votes / total) * 100 : 0;
        const fillW = (pct / 100) * contentWidth;
        const pctText = `${votes} | ${pct.toFixed(1)}%`;
        const optText = fixParens(String(opt.text || ""), isRTL);

        // Truncate option text if it would overlap the percentage label
        const pctW = boldFont.widthOfTextAtSize(pctText, optFontSize);
        const maxOptW = contentWidth - pctW - 12;
        let displayOptText = optText;
        while (displayOptText.length > 0 && font.widthOfTextAtSize(displayOptText, optFontSize) > maxOptW) {
          displayOptText = displayOptText.slice(0, -1);
        }
        if (displayOptText.length < optText.length) displayOptText += "…";

        // Option label (left for LTR, right for RTL)
        const optX = isRTL ? pageWidth - margin - font.widthOfTextAtSize(displayOptText, optFontSize) : margin;
        page.drawText(displayOptText, { x: optX, y: yPosition, size: optFontSize, font, color: COLOR_TEXT_MAIN });

        // Count | percentage (right for LTR, left for RTL)
        const pctX = isRTL ? margin : pageWidth - margin - pctW;
        page.drawText(pctText, { x: pctX, y: yPosition, size: optFontSize, font: boldFont, color: COLOR_TEXT_SECONDARY });

        // Background bar
        const barY = yPosition - optFontSize - 4;
        page.drawRectangle({ x: margin, y: barY, width: contentWidth, height: barH, color: rgb(0.92, 0.92, 0.92) });

        // Fill bar (RTL fills from right to left)
        if (fillW > 0) {
          page.drawRectangle({
            x: isRTL ? margin + contentWidth - fillW : margin,
            y: barY,
            width: fillW,
            height: barH,
            color: COLOR_PRIMARY,
          });
        }

        yPosition -= rowHeight;
      }

      yPosition -= 12;
    }
  }

  // Footer with page numbers
  const pages = pdf.getPages();
  for (let i = 0; i < pages.length; i++) {
    const p = pages[i];
    const pageNumText = activeLanguage === "ar"
      ? `صفحة ${i + 1} من ${pages.length}`
      : `Page ${i + 1} of ${pages.length}`;

    const textWidth = font.widthOfTextAtSize(pageNumText, FONT_PAGENUM);
    p.drawText(pageNumText, {
      x: pageWidth - margin - textWidth,
      y: 10,
      size: FONT_PAGENUM,
      font,
      color: COLOR_TEXT_SECONDARY,
    });

    drawConfidentialFooter(p, pageWidth, font, activeLanguage, margin);
  }

  // Save & download
  const pdfBytes = await pdf.save();
  const blob = new Blob([pdfBytes], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;

  const name = surveyInfo?.title || eventInfo?.name || "insights";
  const sanitizedName = name.replace(/[^a-zA-Z0-9_-]/g, "_").replace(/_+/g, "_").trim();
  link.download = `${sanitizedName}_insights.pdf`;

  link.click();
  URL.revokeObjectURL(url);
};
