export const COUNTRY_CODES = [
    { code: "+93", country: "Afghanistan", isoCode: "af" },
    { code: "+355", country: "Albania", isoCode: "al" },
    { code: "+213", country: "Algeria", isoCode: "dz" },
    { code: "+376", country: "Andorra", isoCode: "ad" },
    { code: "+244", country: "Angola", isoCode: "ao" },
    { code: "+1", country: "Antigua and Barbuda", isoCode: "ag" },
    { code: "+54", country: "Argentina", isoCode: "ar" },
    { code: "+374", country: "Armenia", isoCode: "am" },
    { code: "+61", country: "Australia", isoCode: "au" },
    { code: "+43", country: "Austria", isoCode: "at" },
    { code: "+994", country: "Azerbaijan", isoCode: "az" },
    { code: "+1", country: "Bahamas", isoCode: "bs" },
    { code: "+973", country: "Bahrain", isoCode: "bh" },
    { code: "+880", country: "Bangladesh", isoCode: "bd" },
    { code: "+1", country: "Barbados", isoCode: "bb" },
    { code: "+375", country: "Belarus", isoCode: "by" },
    { code: "+32", country: "Belgium", isoCode: "be" },
    { code: "+501", country: "Belize", isoCode: "bz" },
    { code: "+229", country: "Benin", isoCode: "bj" },
    { code: "+975", country: "Bhutan", isoCode: "bt" },
    { code: "+591", country: "Bolivia", isoCode: "bo" },
    { code: "+387", country: "Bosnia and Herzegovina", isoCode: "ba" },
    { code: "+267", country: "Botswana", isoCode: "bw" },
    { code: "+55", country: "Brazil", isoCode: "br" },
    { code: "+673", country: "Brunei", isoCode: "bn" },
    { code: "+359", country: "Bulgaria", isoCode: "bg" },
    { code: "+226", country: "Burkina Faso", isoCode: "bf" },
    { code: "+257", country: "Burundi", isoCode: "bi" },
    { code: "+855", country: "Cambodia", isoCode: "kh" },
    { code: "+237", country: "Cameroon", isoCode: "cm" },
    { code: "+1", country: "Canada", isoCode: "ca" },
    { code: "+238", country: "Cape Verde", isoCode: "cv" },
    { code: "+236", country: "Central African Republic", isoCode: "cf" },
    { code: "+235", country: "Chad", isoCode: "td" },
    { code: "+56", country: "Chile", isoCode: "cl" },
    { code: "+86", country: "China", isoCode: "cn" },
    { code: "+57", country: "Colombia", isoCode: "co" },
    { code: "+269", country: "Comoros", isoCode: "km" },
    { code: "+242", country: "Congo", isoCode: "cg" },
    { code: "+243", country: "Congo (DRC)", isoCode: "cd" },
    { code: "+506", country: "Costa Rica", isoCode: "cr" },
    { code: "+225", country: "Côte d'Ivoire", isoCode: "ci" },
    { code: "+385", country: "Croatia", isoCode: "hr" },
    { code: "+53", country: "Cuba", isoCode: "cu" },
    { code: "+357", country: "Cyprus", isoCode: "cy" },
    { code: "+420", country: "Czech Republic", isoCode: "cz" },
    { code: "+45", country: "Denmark", isoCode: "dk" },
    { code: "+253", country: "Djibouti", isoCode: "dj" },
    { code: "+1", country: "Dominica", isoCode: "dm" },
    { code: "+1", country: "Dominican Republic", isoCode: "do" },
    { code: "+593", country: "Ecuador", isoCode: "ec" },
    { code: "+20", country: "Egypt", isoCode: "eg" },
    { code: "+503", country: "El Salvador", isoCode: "sv" },
    { code: "+240", country: "Equatorial Guinea", isoCode: "gq" },
    { code: "+291", country: "Eritrea", isoCode: "er" },
    { code: "+372", country: "Estonia", isoCode: "ee" },
    { code: "+268", country: "Eswatini", isoCode: "sz" },
    { code: "+251", country: "Ethiopia", isoCode: "et" },
    { code: "+679", country: "Fiji", isoCode: "fj" },
    { code: "+358", country: "Finland", isoCode: "fi" },
    { code: "+33", country: "France", isoCode: "fr" },
    { code: "+241", country: "Gabon", isoCode: "ga" },
    { code: "+220", country: "Gambia", isoCode: "gm" },
    { code: "+995", country: "Georgia", isoCode: "ge" },
    { code: "+49", country: "Germany", isoCode: "de" },
    { code: "+233", country: "Ghana", isoCode: "gh" },
    { code: "+30", country: "Greece", isoCode: "gr" },
    { code: "+1", country: "Grenada", isoCode: "gd" },
    { code: "+502", country: "Guatemala", isoCode: "gt" },
    { code: "+224", country: "Guinea", isoCode: "gn" },
    { code: "+245", country: "Guinea-Bissau", isoCode: "gw" },
    { code: "+592", country: "Guyana", isoCode: "gy" },
    { code: "+509", country: "Haiti", isoCode: "ht" },
    { code: "+504", country: "Honduras", isoCode: "hn" },
    { code: "+36", country: "Hungary", isoCode: "hu" },
    { code: "+354", country: "Iceland", isoCode: "is" },
    { code: "+91", country: "India", isoCode: "in" },
    { code: "+62", country: "Indonesia", isoCode: "id" },
    { code: "+98", country: "Iran", isoCode: "ir" },
    { code: "+964", country: "Iraq", isoCode: "iq" },
    { code: "+353", country: "Ireland", isoCode: "ie" },
    { code: "+972", country: "Israel", isoCode: "il" },
    { code: "+39", country: "Italy", isoCode: "it" },
    { code: "+1", country: "Jamaica", isoCode: "jm" },
    { code: "+81", country: "Japan", isoCode: "jp" },
    { code: "+962", country: "Jordan", isoCode: "jo" },
    { code: "+7", country: "Kazakhstan", isoCode: "kz" },
    { code: "+254", country: "Kenya", isoCode: "ke" },
    { code: "+686", country: "Kiribati", isoCode: "ki" },
    { code: "+965", country: "Kuwait", isoCode: "kw" },
    { code: "+996", country: "Kyrgyzstan", isoCode: "kg" },
    { code: "+856", country: "Laos", isoCode: "la" },
    { code: "+371", country: "Latvia", isoCode: "lv" },
    { code: "+961", country: "Lebanon", isoCode: "lb" },
    { code: "+266", country: "Lesotho", isoCode: "ls" },
    { code: "+231", country: "Liberia", isoCode: "lr" },
    { code: "+218", country: "Libya", isoCode: "ly" },
    { code: "+423", country: "Liechtenstein", isoCode: "li" },
    { code: "+370", country: "Lithuania", isoCode: "lt" },
    { code: "+352", country: "Luxembourg", isoCode: "lu" },
    { code: "+261", country: "Madagascar", isoCode: "mg" },
    { code: "+265", country: "Malawi", isoCode: "mw" },
    { code: "+60", country: "Malaysia", isoCode: "my" },
    { code: "+960", country: "Maldives", isoCode: "mv" },
    { code: "+223", country: "Mali", isoCode: "ml" },
    { code: "+356", country: "Malta", isoCode: "mt" },
    { code: "+692", country: "Marshall Islands", isoCode: "mh" },
    { code: "+222", country: "Mauritania", isoCode: "mr" },
    { code: "+230", country: "Mauritius", isoCode: "mu" },
    { code: "+52", country: "Mexico", isoCode: "mx" },
    { code: "+691", country: "Micronesia", isoCode: "fm" },
    { code: "+373", country: "Moldova", isoCode: "md" },
    { code: "+377", country: "Monaco", isoCode: "mc" },
    { code: "+976", country: "Mongolia", isoCode: "mn" },
    { code: "+382", country: "Montenegro", isoCode: "me" },
    { code: "+212", country: "Morocco", isoCode: "ma" },
    { code: "+258", country: "Mozambique", isoCode: "mz" },
    { code: "+95", country: "Myanmar", isoCode: "mm" },
    { code: "+264", country: "Namibia", isoCode: "na" },
    { code: "+674", country: "Nauru", isoCode: "nr" },
    { code: "+977", country: "Nepal", isoCode: "np" },
    { code: "+31", country: "Netherlands", isoCode: "nl" },
    { code: "+64", country: "New Zealand", isoCode: "nz" },
    { code: "+505", country: "Nicaragua", isoCode: "ni" },
    { code: "+227", country: "Niger", isoCode: "ne" },
    { code: "+234", country: "Nigeria", isoCode: "ng" },
    { code: "+850", country: "North Korea", isoCode: "kp" },
    { code: "+389", country: "North Macedonia", isoCode: "mk" },
    { code: "+47", country: "Norway", isoCode: "no" },
    { code: "+968", country: "Oman", isoCode: "om" },
    { code: "+92", country: "Pakistan", isoCode: "pk" },
    { code: "+680", country: "Palau", isoCode: "pw" },
    { code: "+970", country: "Palestine", isoCode: "ps" },
    { code: "+507", country: "Panama", isoCode: "pa" },
    { code: "+675", country: "Papua New Guinea", isoCode: "pg" },
    { code: "+595", country: "Paraguay", isoCode: "py" },
    { code: "+51", country: "Peru", isoCode: "pe" },
    { code: "+63", country: "Philippines", isoCode: "ph" },
    { code: "+48", country: "Poland", isoCode: "pl" },
    { code: "+351", country: "Portugal", isoCode: "pt" },
    { code: "+974", country: "Qatar", isoCode: "qa" },
    { code: "+40", country: "Romania", isoCode: "ro" },
    { code: "+7", country: "Russia", isoCode: "ru" },
    { code: "+250", country: "Rwanda", isoCode: "rw" },
    { code: "+1", country: "Saint Kitts and Nevis", isoCode: "kn" },
    { code: "+1", country: "Saint Lucia", isoCode: "lc" },
    { code: "+1", country: "Saint Vincent and the Grenadines", isoCode: "vc" },
    { code: "+685", country: "Samoa", isoCode: "ws" },
    { code: "+378", country: "San Marino", isoCode: "sm" },
    { code: "+239", country: "Sao Tome and Principe", isoCode: "st" },
    { code: "+966", country: "Saudi Arabia", isoCode: "sa" },
    { code: "+221", country: "Senegal", isoCode: "sn" },
    { code: "+381", country: "Serbia", isoCode: "rs" },
    { code: "+248", country: "Seychelles", isoCode: "sc" },
    { code: "+232", country: "Sierra Leone", isoCode: "sl" },
    { code: "+65", country: "Singapore", isoCode: "sg" },
    { code: "+421", country: "Slovakia", isoCode: "sk" },
    { code: "+386", country: "Slovenia", isoCode: "si" },
    { code: "+677", country: "Solomon Islands", isoCode: "sb" },
    { code: "+252", country: "Somalia", isoCode: "so" },
    { code: "+27", country: "South Africa", isoCode: "za" },
    { code: "+82", country: "South Korea", isoCode: "kr" },
    { code: "+211", country: "South Sudan", isoCode: "ss" },
    { code: "+34", country: "Spain", isoCode: "es" },
    { code: "+94", country: "Sri Lanka", isoCode: "lk" },
    { code: "+249", country: "Sudan", isoCode: "sd" },
    { code: "+597", country: "Suriname", isoCode: "sr" },
    { code: "+46", country: "Sweden", isoCode: "se" },
    { code: "+41", country: "Switzerland", isoCode: "ch" },
    { code: "+963", country: "Syria", isoCode: "sy" },
    { code: "+886", country: "Taiwan", isoCode: "tw" },
    { code: "+992", country: "Tajikistan", isoCode: "tj" },
    { code: "+255", country: "Tanzania", isoCode: "tz" },
    { code: "+66", country: "Thailand", isoCode: "th" },
    { code: "+670", country: "Timor-Leste", isoCode: "tl" },
    { code: "+228", country: "Togo", isoCode: "tg" },
    { code: "+676", country: "Tonga", isoCode: "to" },
    { code: "+1", country: "Trinidad and Tobago", isoCode: "tt" },
    { code: "+216", country: "Tunisia", isoCode: "tn" },
    { code: "+90", country: "Turkey", isoCode: "tr" },
    { code: "+993", country: "Turkmenistan", isoCode: "tm" },
    { code: "+1", country: "Tuvalu", isoCode: "tv" },
    { code: "+256", country: "Uganda", isoCode: "ug" },
    { code: "+380", country: "Ukraine", isoCode: "ua" },
    { code: "+971", country: "United Arab Emirates", isoCode: "ae" },
    { code: "+44", country: "United Kingdom", isoCode: "gb" },
    { code: "+1", country: "United States", isoCode: "us" },
    { code: "+598", country: "Uruguay", isoCode: "uy" },
    { code: "+998", country: "Uzbekistan", isoCode: "uz" },
    { code: "+678", country: "Vanuatu", isoCode: "vu" },
    { code: "+379", country: "Vatican City (Holy See)", isoCode: "va" },
    { code: "+58", country: "Venezuela", isoCode: "ve" },
    { code: "+84", country: "Vietnam", isoCode: "vn" },
    { code: "+967", country: "Yemen", isoCode: "ye" },
    { code: "+260", country: "Zambia", isoCode: "zm" },
    { code: "+263", country: "Zimbabwe", isoCode: "zw" },
];

export const DEFAULT_COUNTRY_CODE = "+968";

export const getFlagImageUrl = (isoCode) => {
    return `https://flagcdn.com/w20/${isoCode.toLowerCase()}.png`;
};

export const getCountryCodeByCode = (code) => {
    return COUNTRY_CODES.find((cc) => cc.code === code) || COUNTRY_CODES[0];
};
